services:
  # Servicio para la base de datos MongoDB
  db-peppercrm:
    image: sebastian190030/db-peppercrm:latest
    container_name: peppercrm-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - peppercrm-network

  # Servicio para cache de Redis
  cache-peppercrm:
    image: sebastian190030/cache-peppercrm:latest
    container_name: peppercrm-cache
    ports:
      - "6379:6379"
    networks:
      - peppercrm-network

  # Servicio para correo de mailpit
  mail-peppercrm:
    image: sebastian190030/mail-peppercrm:latest
    container_name: peppercrm-mail
    ports:
      - "8025:8025" # GUI port
      - "1025:1025" # SMTP Port
    volumes:
      - ./authfile:/app/authfile
    command: ["--smtp-auth-file=/app/authfile", "--smtp-auth-allow-insecure"]
    networks:
      - peppercrm-network

  # Servicio para la API
  api-peppercrm:
    image: sebastian190030/api-peppercrm:latest
    container_name: peppercrm-api
    environment:
      # Configuración APP
      - APP_NAME=PepperCRM-API
      - PORT=8091
      - TITLE=peppercrm API
      - DESCRIPTION=Documentación de la API REST de PepperCRM
      - VERSION=1.0.0
      - AUTHOR=peppercrm Developers

      # MongoDB
      - DATA_CONNECTION_METHOD=mongodb
      - DATA_SOURCE_USERNAME=admin
      - DATA_SOURCE_PASSWORD=admin
      - DATA_SOURCE_DOMAIN=db-peppercrm:27017
      - DATA_SOURCE_DB=peppercrm
      - DATA_PARAMS=authSource=admin&directConnection=true&serverSelectionTimeoutMS=100000&socketTimeoutMS=10000&appName=mongo

      # Redis
      - CACHE_TYPE=redis
      - CACHE_HOST=cache-peppercrm
      - CACHE_PORT=6379
      - CACHE_DB=0
      - CACHE_USERNAME=default
      - CACHE_PASSWORD=redislocalpass
      - CACHE_TIMEOUT=2000
      - CACHE_LETTUCE_POOL_MAX_ACTIVE=8
      - CACHE_LETTUCE_POOL_MAX_WAIT=-1
      - CACHE_LETTUCE_POOL_MAX_IDLE=8
      - CACHE_LETTUCE_POOL_MIN_IDLE=8

      # Config cache
      - CACHE_TIME_TO_LIVE=300000
      - CACHE_NULL_VALUES=false

      # Email (usando mailpit en local)
      - MAIL_HOST=mail-peppercrm
      - MAIL_PORT=1025
      - MAIL_USERNAME=peppertechdev@example.com
      - MAIL_PASSWORD=correo1234
      - MAIL_PROPERTIES_SMTP_AUTH=true
      - MAIL_PROPERTIES_SMTP_STARTTLS_ENABLE=false

      # Telegram
      - TELEGRAM_BOT_TOKEN=mocked:token:for:telegram:testing

      # Seguridad
      - SECURITY_JWT_SECRET_KEY=c8e9b6803afbcfa6edd9569c94c75ff4b144622b0a0570a636dffd62c24a3476
      - SECURITY_JWT_EXPIRATION=86400000
      - SECURITY_PUBLIC_ROUTES=/auth/login,/auth/verify

      # Rate limiting
      - RATE_LIMITING_MAX_REQUESTS=5
      - RATE_LIMITING_TIME_WINDOW=60000
      - RATE_LIMITING_PUBLIC_ROUTES=/swagger-ui/,/v3/api-docs,/swagger-resources/,/webjars/

      # Headers
      - HEADER_CORS_ALLOWED_ORIGINS=http://localhost:5173

      # Tomcat
      - SERVER_TOMCAT_TIMEOUT=600000

      # Debugger
      - DEBUGGER_MODE=INFO
    ports:
      - "8091:8091"
    depends_on:
      - db-peppercrm
      - cache-peppercrm
    networks:
      - peppercrm-network

  # Servicio para la aplicación web
  web-peppercrm:
    image: sebastian190030/web-peppercrm:latest
    container_name: peppercrm-web
    environment:
      - VITE_API_BASE_URL=http://localhost:8091
    ports:
      - "5173:5173"
    networks:
      - peppercrm-network

# Volúmenes para persistencia de datos
volumes:
  mongo_data:

# Red de contenedores para comunicación entre servicios
networks:
  peppercrm-network:
    driver: bridge
